name: Build Luci App NVR IPK

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialization environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5-dev gawk git gettext libssl-dev xsltproc wget unzip

      - name: Compile IPK
        run: |
          # 1. 下载 SDK
          wget https://downloads.openwrt.org/releases/23.05.0/targets/x86/64/openwrt-sdk-23.05.0-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz
          
          # 2. 创建 sdk 目录并解压内容（丢弃原始长文件夹名）
          mkdir sdk
          tar xJf openwrt-sdk-*.tar.xz -C sdk --strip-components=1
          
          # 3. 将你的项目代码放入 SDK
          mkdir -p sdk/package/luci-app-nvr
          cp -r ./* sdk/package/luci-app-nvr/
          # 排除 sdk 目录自身，防止无限嵌套
          rm -rf sdk/package/luci-app-nvr/sdk
          
          # 4. 进入 SDK 目录编译
          cd sdk
          # 更新 Feeds (确保基础依赖可用)
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          # 配置并编译
          make defconfig
          make package/luci-app-nvr/compile V=s

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: luci-app-nvr-ipk
          path: |
            sdk/bin/packages/x86_64/**/luci-app-nvr*.ipk
