name: Build Luci App NVR IPK

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialization environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5-dev gawk git gettext libssl-dev xsltproc wget unzip

      - name: Compile IPK
        run: |
          # 1. 清理环境并下载 SDK
          rm -rf openwrt-sdk-*
          wget https://downloads.openwrt.org/releases/23.05.0/targets/x86/64/openwrt-sdk-23.05.0-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz
          
          # 2. 解压并重命名文件夹，解决路径不确定的问题
          mkdir sdk
          tar xJf openwrt-sdk-*.tar.xz -C sdk --strip-components=1
          
          # 3. 准备项目代码
          mkdir -p sdk/package/luci-app-nvr
          cp -r ./* sdk/package/luci-app-nvr/
          rm -rf sdk/package/luci-app-nvr/sdk  # 防止循环拷贝
          
          # 4. 进入固定的 sdk 目录编译
          cd sdk
          make defconfig
          make package/luci-app-nvr/compile V=s

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: luci-app-nvr-ipk
          path: |
            openwrt-sdk-*/bin/packages/x86_64/base/luci-app-nvr*.ipk
            openwrt-sdk-*/bin/packages/x86_64/action/luci-app-nvr*.ipk
