name: Build Luci App NVR IPK

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialization environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5-dev gawk git gettext libssl-dev xsltproc wget unzip

      - name: Compile IPK
        run: |
          # 1. 下载并解压 SDK
          wget https://downloads.openwrt.org/releases/23.05.0/targets/x86/64/openwrt-sdk-23.05.0-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz
          tar xJf openwrt-sdk-*.tar.xz
          
          # 2. 获取解压后的文件夹名称
          SDK_DIR=$(ls -d openwrt-sdk-*)
          
          # 3. 将代码拷贝进 SDK (排除 SDK 自身)
          mkdir -p "$SDK_DIR/package/luci-app-nvr"
          find . -maxdepth 1 ! -name "$SDK_DIR" ! -name "*.tar.xz" ! -name "." -exec cp -r {} "$SDK_DIR/package/luci-app-nvr/" \;
          
          # 4. 进入目录编译
          cd "$SDK_DIR"
          make defconfig
          make package/luci-app-nvr/compile V=s

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: luci-app-nvr-ipk
          path: |
            openwrt-sdk-*/bin/packages/x86_64/base/luci-app-nvr*.ipk
            openwrt-sdk-*/bin/packages/x86_64/action/luci-app-nvr*.ipk
